# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7dba77fc19a55e1107f98ec1378233519f945ae194b353183a1dbbac02cb194e884c7fa8b07bbe957b0761e739597958f240c8d35864b26a9001b5554aa40e7c

test:
  secret_key_base: e3a6e24ccdd41af908febe342c31ea20eb07a245b8b2dc84d49092d6541b1fff299493e5ac2653f81331abc1bdc2fe80b9c80074be8a3f233396fd9a1bca8545

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
